(() => {
  window.APPRAISAL_CASE_DATA = {
evidenceCatalog: {
  pricePoint: {
    term: "価格時点",
    title: "2026-05-05時点の正常価格",
    detail: "いつの時点の価値を評価するかを固定した。",
    scores: { appraisal: 6, ethics: 4 },
  },
  subjectProperty: {
    term: "対象不動産の確定",
    title: "川辺町3丁目17番5の土地建物",
    detail: "依頼者の希望ではなく、登記・現況・資料で評価対象を特定する。",
    scores: { appraisal: 6 },
  },
  wallCrack: {
    term: "個別的要因",
    title: "外壁劣化の痕跡",
    detail: "建物状態が対象不動産の個別的要因として価格判断に影響する。",
    scores: { investigation: 7, appraisal: 2 },
  },
  boundary: {
    term: "対象不動産の確定",
    title: "隣地境界と越境疑い",
    detail: "境界未確定や越境は評価対象の確定と市場性に影響する。",
    scores: { investigation: 9, reasoning: 4, appraisal: 4 },
  },
  tower: {
    term: "地域要因",
    title: "背後の鉄塔と嫌悪施設隣接",
    detail: "周辺環境の価格形成要因として減価検討が必要。",
    scores: { investigation: 8, appraisal: 4 },
  },
  road: {
    term: "個別的要因",
    title: "前面道路幅員が狭い",
    detail: "接道条件不良は取引事例比較法の個別的要因比較で反映する。",
    scores: { investigation: 8, appraisal: 5 },
  },
  utility: {
    term: "現地調査",
    title: "引込設備の老朽化",
    detail: "設備更新コストが買主の価格判断に影響する可能性がある。",
    scores: { investigation: 5 },
  },
  areaMismatch: {
    term: "対象不動産の確定",
    title: "依頼者説明60坪、登記55坪",
    detail: "評価対象面積の食い違い。依頼者説明だけで進めると過大評価になる。",
    scores: { reasoning: 10, appraisal: 8, ethics: 3 },
  },
  specialTransaction: {
    term: "事情補正",
    title: "取引事例Bは親族間売買",
    detail: "通常の市場取引ではないため、採用には事情補正の検討が必要。",
    scores: { reasoning: 10, appraisal: 8 },
  },
  timeAdjustment: {
    term: "時点修正",
    title: "取引事例Cは18か月前の成約",
    detail: "価格時点までの市場変動を反映しないと比較精度が落ちる。",
    scores: { reasoning: 7, appraisal: 5 },
  },
  comparableA: {
    term: "取引事例比較法",
    title: "事例Aを主たる比較対象に採用",
    detail: "同一需給圏、用途、規模、接道条件が最も近い。",
    scores: { appraisal: 10, reasoning: 5 },
  },
  riskAdjustment: {
    term: "試算価格の調整",
    title: "接道・越境・嫌悪施設を減価要因として反映",
    detail: "比準価格を機械的に採用せず、発見した個別リスクを調整した。",
    scores: { appraisal: 10, reasoning: 4 },
  },
  incomePricePoint: {
    term: "価格時点",
    title: "2026-05-05時点の収益価格",
    detail: "賃料や空室率を、価格時点の市場前提に固定した。",
    scores: { appraisal: 6, ethics: 4 },
  },
  incomeSubject: {
    term: "対象不動産の確定",
    title: "駅前第3ビルの土地建物",
    detail: "店舗、事務所、共用部、契約対象面積を評価対象として確定した。",
    scores: { appraisal: 7 },
  },
  tenantMix: {
    term: "収益性",
    title: "1階店舗の賃料依存が大きい",
    detail: "一部テナントへの依存は、将来収益の安定性に影響する。",
    scores: { investigation: 7, appraisal: 4 },
  },
  vacancySign: {
    term: "空室リスク",
    title: "3階区画に長期空室の掲示",
    detail: "空室率の見込みは純収益と収益価格に直接影響する。",
    scores: { investigation: 9, reasoning: 4, appraisal: 5 },
  },
  repairBacklog: {
    term: "必要諸経費",
    title: "外壁と空調更新の遅れ",
    detail: "修繕費や更新費を見落とすと、純収益を過大に見る。",
    scores: { investigation: 8, appraisal: 5 },
  },
  roadFlow: {
    term: "地域要因",
    title: "駅前動線は強いが裏通り化が進む",
    detail: "人通りの変化は店舗賃料と将来の収益性に影響する。",
    scores: { investigation: 6, reasoning: 3, appraisal: 3 },
  },
  signLease: {
    term: "賃貸借契約",
    title: "看板区画は短期契約",
    detail: "一時的な広告収入を安定収益として扱うと過大評価になる。",
    scores: { investigation: 5, reasoning: 5, appraisal: 3 },
  },
  rentRoll: {
    term: "賃料水準",
    title: "レントロールに市場賃料との差",
    detail: "現行賃料と市場賃料の差を確認し、持続可能な総収益を見積もる。",
    scores: { reasoning: 10, appraisal: 8 },
  },
  expenseLeak: {
    term: "必要諸経費",
    title: "管理費と修繕費が過少計上",
    detail: "純収益を求めるには、維持管理費、修繕費、空室損を控除する必要がある。",
    scores: { reasoning: 9, appraisal: 8, ethics: 2 },
  },
  capRateGap: {
    term: "還元利回り",
    title: "依頼者提示の利回りが低すぎる",
    detail: "リスクに見合わない還元利回りは、収益価格を過大にする。",
    scores: { reasoning: 10, appraisal: 10, ethics: 3 },
  },
  directCap: {
    term: "直接還元法",
    title: "安定純収益を還元して収益価格を査定",
    detail: "一期間の標準化した純収益を、適切な還元利回りで資本還元する。",
    scores: { appraisal: 12, reasoning: 6 },
  },
  incomeAdjustment: {
    term: "収益価格の査定",
    title: "空室・修繕・利回りリスクを反映",
    detail: "収益価格を依頼者の融資希望額に寄せず、収益リスクで調整した。",
    scores: { appraisal: 12, reasoning: 5, ethics: 4 },
  },
  redevelopmentPricePoint: {
    term: "価格時点",
    title: "2026-05-05時点の開発素地価格",
    detail: "再開発期待を、価格時点で実現可能な前提に固定した。",
    scores: { appraisal: 6, ethics: 4 },
  },
  redevelopmentSubject: {
    term: "対象不動産の確定",
    title: "南口再開発予定地の土地建物",
    detail: "複数筆、既存建物、借家人、前面道路との関係を評価対象として確定した。",
    scores: { appraisal: 7 },
  },
  tenantRights: {
    term: "権利関係",
    title: "現入居テナントの立退き未了",
    detail: "借家人の存在は開発時期、費用、実現可能性に影響する。",
    scores: { investigation: 9, reasoning: 4, appraisal: 5, ethics: 2 },
  },
  narrowAlley: {
    term: "接道条件",
    title: "南側路地の幅員不足",
    detail: "道路後退や搬入動線の制約は、開発計画と土地価格に影響する。",
    scores: { investigation: 8, appraisal: 6 },
  },
  zoningMismatch: {
    term: "公法上の規制",
    title: "容積率想定と高度地区の制約",
    detail: "依頼者の最大容積案は、高度地区と斜線制限を無視している可能性がある。",
    scores: { investigation: 8, reasoning: 7, appraisal: 7 },
  },
  floodHistory: {
    term: "地域要因",
    title: "低地の浸水履歴",
    detail: "災害履歴は用途、建築費、販売価格、需要者心理に影響する。",
    scores: { investigation: 7, appraisal: 5 },
  },
  oldWarehouse: {
    term: "個別的要因",
    title: "既存倉庫の解体リスク",
    detail: "老朽建物の解体費や有害物調査を見落とすと、開発素地価格を過大に見る。",
    scores: { investigation: 7, appraisal: 5 },
  },
  zoningCheck: {
    term: "公法上の規制",
    title: "高度地区・斜線制限を確認",
    detail: "最有効使用は、法令上実現可能な建物ボリュームを前提に判定する。",
    scores: { reasoning: 10, appraisal: 9 },
  },
  relocationCost: {
    term: "権利調整",
    title: "立退料と交渉期間を控除",
    detail: "開発法では、借家人対応に要する費用と期間リスクを反映する。",
    scores: { reasoning: 10, appraisal: 9, ethics: 3 },
  },
  infrastructureBurden: {
    term: "開発負担",
    title: "道路後退と公共負担を確認",
    detail: "有効宅地面積と開発費を調整しないと、素地価格を過大評価する。",
    scores: { reasoning: 8, appraisal: 8 },
  },
  developmentMethod: {
    term: "開発法",
    title: "開発後販売総額から費用を控除",
    detail: "完成後の販売総額から建築費、販売費、利潤、期間リスクを控除して素地価格を求める。",
    scores: { appraisal: 12, reasoning: 6 },
  },
  bestUseAdjustment: {
    term: "最有効使用",
    title: "中層共同住宅＋低層店舗が妥当",
    detail: "現況利用でも最大容積案でもなく、合法性、物理性、市場性を満たす用途を採用した。",
    scores: { appraisal: 12, reasoning: 7, ethics: 3 },
  },
},

caseHotspots: {
  case001: [
    { id: "wallCrack", label: "1", x: 39, y: 52 },
    { id: "boundary", label: "2", x: 28, y: 76 },
    { id: "tower", label: "3", x: 87, y: 32 },
    { id: "road", label: "4", x: 77, y: 84 },
    { id: "utility", label: "5", x: 66, y: 39 },
  ],
  case002: [
    { id: "tenantMix", label: "1", x: 34, y: 47 },
    { id: "vacancySign", label: "2", x: 62, y: 31 },
    { id: "repairBacklog", label: "3", x: 46, y: 23 },
    { id: "roadFlow", label: "4", x: 78, y: 78 },
    { id: "signLease", label: "5", x: 22, y: 28 },
  ],
  case003: [
    { id: "tenantRights", label: "1", x: 31, y: 54 },
    { id: "narrowAlley", label: "2", x: 68, y: 80 },
    { id: "zoningMismatch", label: "3", x: 76, y: 23 },
    { id: "floodHistory", label: "4", x: 17, y: 77 },
    { id: "oldWarehouse", label: "5", x: 51, y: 40 },
  ],
},

caseDecoyHotspots: {
  case001: [
    {
      id: "gardenLantern",
      label: "D1",
      title: "庭石と外灯",
      lesson: "見た目の古さだけでは個別的要因にならない。価格形成要因として説明できる根拠を優先する。",
    },
    {
      id: "freshCurtain",
      label: "D2",
      title: "新しいカーテン",
      lesson: "動産や一時的な印象は、土地建物の正常価格を支える根拠になりにくい。",
    },
  ],
  case002: [
    {
      id: "busyCafe",
      label: "D1",
      title: "混雑している1階カフェ",
      lesson: "一時的な客入りだけでは収益価格の根拠にならない。契約条件と継続賃料を確認する。",
    },
    {
      id: "newPoster",
      label: "D2",
      title: "新しい販促ポスター",
      lesson: "販促物は短期的な営業努力であり、純収益や還元利回りの判断材料とは分ける。",
    },
  ],
  case003: [
    {
      id: "salesBanner",
      label: "D1",
      title: "開発予定の告知幕",
      lesson: "事業者の期待や広告は、最有効使用の根拠ではない。法令、権利、市場性を確認する。",
    },
    {
      id: "cleanFacade",
      label: "D2",
      title: "塗り直された倉庫正面",
      lesson: "外観の印象だけでは開発負担を判断できない。既存建物、解体費、権利関係を拾う。",
    },
  ],
},

caseDocumentPanels: {
  case001: [
    {
      title: "登記・地図",
      items: [
        "登記地積: 181.81平方メートル",
        "依頼者説明: 約60坪",
        "前面道路: 建築基準法42条2項道路",
      ],
    },
    {
      title: "取引事例",
      items: [
        "事例A: 同一町内、標準的住宅地、6か月前",
        "事例B: 近隣、親族間売買、3か月前",
        "事例C: 駅近、道路条件良好、18か月前",
      ],
    },
  ],
  case002: [
    {
      title: "レントロール",
      items: [
        "1F店舗: 月額95万円、売上歩合なし",
        "2F事務所: 月額42万円、残存契約18か月",
        "3F区画: 空室8か月、募集賃料は相場より高い",
        "屋上看板: 短期契約、解約予告1か月",
      ],
    },
    {
      title: "収支・利回り",
      items: [
        "依頼者想定還元利回り: 4.2%",
        "近隣小規模ビル取引: 5.3-5.8%",
        "管理費: 前年度比で30%圧縮",
        "修繕積立: 空調更新費が未計上",
      ],
    },
  ],
  case003: [
    {
      title: "都市計画・道路",
      items: [
        "用途地域: 商業地域、指定容積率400%",
        "高度地区: 第3種、北側斜線の影響あり",
        "南側路地: 現況幅員3.2m、後退協議が必要",
        "ハザード: 既往浸水区域に接する",
      ],
    },
    {
      title: "権利・開発収支",
      items: [
        "既存テナント: 2件、普通借家契約",
        "依頼者計画: 14階マンション＋1階店舗",
        "販売想定: 駅近プレミアムを強めに設定",
        "控除漏れ: 立退料、解体費、販売期間リスク",
      ],
    },
  ],
},

caseDocumentIssues: {
  case001: [
    {
      id: "areaMismatch",
      title: "登記簿と依頼者説明を照合",
      detail: "依頼者は60坪と言ったが、登記簿は55坪。",
    },
    {
      id: "specialTransaction",
      title: "取引事例Bの売買事情を確認",
      detail: "近隣売買だが、売主買主が親族関係。",
    },
    {
      id: "timeAdjustment",
      title: "取引事例Cの取引時点を確認",
      detail: "条件は似ているが、成約は18か月前。",
    },
  ],
  case002: [
    {
      id: "rentRoll",
      title: "レントロールと現況を照合",
      detail: "3階区画は空室8か月。現行賃料を満室前提で見てはいけない。",
    },
    {
      id: "expenseLeak",
      title: "管理費・修繕費の過少計上を確認",
      detail: "外壁と空調更新が未反映で、純収益が過大に見える。",
    },
    {
      id: "capRateGap",
      title: "依頼者提示利回りと市場利回りを比較",
      detail: "提示4.2%に対し、近隣取引は5.3-5.8%。リスク反映が不足。",
    },
  ],
  case003: [
    {
      id: "zoningCheck",
      title: "都市計画図と高度地区を照合",
      detail: "依頼者の最大容積案は、斜線制限と高度地区で削られる。",
    },
    {
      id: "relocationCost",
      title: "賃貸借契約と立退き条件を確認",
      detail: "現入居テナント2件の契約が残り、立退料と期間リスクが必要。",
    },
    {
      id: "infrastructureBurden",
      title: "道路後退と開発負担を確認",
      detail: "南側路地の後退で、有効宅地面積と搬入計画が変わる。",
    },
  ],
},

caseDocumentDecoys: {
  case001: [
    {
      id: "renovationQuote",
      title: "室内リフォーム見積",
      detail: "壁紙と水回りの更新見積。建物印象を強く左右しそうに見える。",
      lesson: "内装見積は建物状態の参考にはなるが、土地の面積差、接道、取引事情より優先する根拠にはならない。",
    },
  ],
  case002: [
    {
      id: "campaignSales",
      title: "飲食店の週末売上メモ",
      detail: "イベント期間中の売上増が記録された店舗メモ。",
      lesson: "一時的な売上は継続賃料や空室率とは別物。収益還元法では安定的な純収益を標準化する。",
    },
  ],
  case003: [
    {
      id: "pressRelease",
      title: "再開発のプレス資料",
      detail: "事業者発表の完成イメージと地域活性化コメント。",
      lesson: "プレス資料は期待であり鑑定評価の根拠ではない。公法規制、権利調整、市場性で実現可能性を検証する。",
    },
  ],
},

caseMechanics: {
  case001: {
    term: "地積換算",
    title: "坪数の食い違いをどう処理するか",
    prompt: "依頼者説明60坪と登記181.81平方メートルを並べ、対象不動産の確定を先に閉じる。",
    input: {
      id: "areaTsubo",
      label: "登記地積を坪へ概算入力",
      suffix: "坪",
      placeholder: "例: 55.0",
      min: 54,
      max: 56,
      formula: "181.81平方メートル ÷ 3.3057 ≒ 55.0坪",
      success: "181.81平方メートルは約55.0坪。依頼者説明60坪との差を面積不一致として扱える。",
      lesson: "181.81平方メートルは約55坪。60坪をそのまま採ると、対象面積を約9%過大に置くことになる。",
      scores: { reasoning: 5, appraisal: 3 },
      penalty: { reasoning: -3, appraisal: -2 },
    },
    choices: [
      {
        id: "registryArea",
        label: "登記地積55坪を基準にする",
        detail: "181.81平方メートルを坪換算し、依頼者説明との差を面積不一致として扱う。",
        correct: true,
        scores: { reasoning: 6, appraisal: 4 },
        mentor: "対象不動産の確定が先だ。地積差は比準価格にも裁量判断にも効く。",
      },
      {
        id: "clientArea",
        label: "依頼者説明60坪を採用する",
        detail: "相続説明を優先し、登記との差は軽微として扱う。",
        correct: false,
        scores: { reasoning: -4, ethics: -3 },
        lesson: "対象不動産の確定前に依頼者説明を採用すると、正常価格の前提が崩れる。",
      },
    ],
  },
  case002: {
    term: "DCR確認",
    title: "借入返済余裕を収益資料で検算する",
    prompt: "満室想定NOIと空室反映後NOIを比べ、融資希望額に引っ張られていないかを確認する。",
    input: {
      id: "stabilizedNoiInput",
      label: "空室・修繕控除後NOIを概算入力",
      suffix: "万円/年",
      placeholder: "例: 1350",
      min: 1320,
      max: 1380,
      formula: "満室NOI 1,620万円 - 空室損 180万円 - 修繕費 90万円 = 1,350万円",
      success: "安定NOIは約1,350万円。満室想定から空室損と修繕費を控除して、DCRと利回り判断へ戻せる。",
      lesson: "満室NOI 1,620万円をそのまま使うと、空室損と修繕費を抜いた返済余裕に見えてしまう。",
      scores: { reasoning: 6, appraisal: 4 },
      penalty: { reasoning: -4, appraisal: -3 },
    },
    choices: [
      {
        id: "stabilizedNoi",
        label: "空室・修繕後の安定純収益で見る",
        detail: "3階空室と修繕費を反映し、DCRが薄い前提を利回り判断へ戻す。",
        correct: true,
        scores: { reasoning: 7, appraisal: 5 },
        mentor: "融資目的は聞く。ただし収益価格は安定純収益で返済余裕を検算して説明する。",
      },
      {
        id: "fullOccupancy",
        label: "満室想定NOIで銀行向けに整える",
        detail: "空室は一時的として、依頼者の借換計画に近い収益を採用する。",
        correct: false,
        scores: { appraisal: -5, ethics: -3 },
        lesson: "満室想定だけに寄せると、空室率、必要諸経費、還元利回りの説明が弱くなる。",
      },
    ],
  },
  case003: {
    term: "用途地域マップ",
    title: "最大容積案を法規制マップで切る",
    prompt: "用途地域、高度地区、前面道路幅員、浸水履歴を重ね、最有効使用を絞る。",
    input: {
      id: "legalFloorInput",
      label: "斜線後の実現階数を概算入力",
      suffix: "階",
      placeholder: "例: 10",
      min: 9,
      max: 11,
      formula: "14階案 → 高度地区・北側斜線・道路後退を重ねると実現目安は10階前後",
      success: "14階案は法規制と道路後退で10階前後まで現実化される。最大容積案をそのまま販売総額に入れない判断につながる。",
      lesson: "14階案をそのまま採ると、高度地区、北側斜線、道路後退による建築可能ボリュームの減少を見落とす。",
      scores: { reasoning: 6, appraisal: 5 },
      penalty: { reasoning: -4, appraisal: -4 },
      visual: {
        planned: "依頼者案 14F",
        limit: "高度地区・斜線ライン",
        feasible: "実現目安 10F",
        note: "用途地域400%でも、斜線と道路後退を重ねると使える床は削られる。",
      },
    },
    choices: [
      {
        id: "legalVolume",
        label: "高度地区と道路後退を反映する",
        detail: "14階案をそのまま採らず、合法性と物理的可能性から開発法の前提を絞る。",
        correct: true,
        scores: { reasoning: 7, appraisal: 6 },
        mentor: "最有効使用は願望ではない。法規制マップで最大容積案を現実化できた。",
      },
      {
        id: "developerPlan",
        label: "依頼者の14階計画を前提にする",
        detail: "地権者説明に合わせ、最大容積消化の販売総額を採用する。",
        correct: false,
        scores: { appraisal: -6, ethics: -3 },
        lesson: "事業者計画を先に採ると、合法性、権利調整、市場性を検証する前に結論へ寄ってしまう。",
      },
    ],
  },
},

caseDefinitions: {
  case001: {
    number: "案件 001",
    title: "川辺町住宅地 / 相続時価把握",
    shortTitle: "川辺町住宅地",
    type: "国内住宅地",
    difficulty: {
      label: "イージー",
      code: "Easy",
      summary: "初回向け。専門用語を画面内で説明し、何を選ぶべきかの考え方まで補助する。",
    },
    image: "./assets/kawabe-estate.generated.png",
    fallbackImage: "./assets/kawabe-estate.svg",
    imageAlt: "川辺町の住宅地外観。古い住宅、狭い道路、境界、鉄塔が見える。",
    assetRefs: {
      fieldImage: "assets/kawabe-estate.generated.png",
      clientPortrait: "assets/tanaka-client.generated.png",
    },
    client: {
      name: "田中修一",
      initial: "田",
      portrait: "./assets/tanaka-client.generated.png",
      portraitClass: "portrait-tanaka",
      tension: "相続で妹を説得したい兄。依頼者の都合を聞きすぎると、評価額への要求が次第に強くなる。",
      gameplayLines: {
        field: "古い家なのは分かっています。でも、思い出まで減点されるんですか。",
        documents: "面積や名義の話、妹にどう説明すればいいんでしょう。",
        appraisal: "低く出ると、妹との話し合いが崩れます。根拠の範囲で上側に見られませんか。",
        report: "せめて兄妹で揉めない言い方にできませんか。",
      },
    },
    evidenceIds: [
      "pricePoint",
      "subjectProperty",
      "wallCrack",
      "boundary",
      "tower",
      "road",
      "utility",
      "areaMismatch",
      "specialTransaction",
      "timeAdjustment",
      "comparableA",
      "riskAdjustment",
    ],
    requiredReport: ["areaMismatch", "specialTransaction", "riskAdjustment"],
    reportStructure: {
      fact: ["areaMismatch", "boundary", "road", "tower", "wallCrack"],
      analysis: ["specialTransaction", "timeAdjustment", "comparableA"],
      conclusion: ["riskAdjustment", "subjectProperty", "pricePoint"],
    },
    hbuMatrix: {
      title: "最有効使用の前提確認",
      lead: "住宅地でも最有効使用は前提。ここでは、標準的な戸建住宅地として使い続ける前提が市場参加者に自然かを確認する。",
      rows: [
        ["法的可能性", "住居系用途として整合。接道条件は価格へ反映する。"],
        ["物理的可能性", "既存住宅は老朽化。境界・道路・設備が買主の改修判断に影響する。"],
        ["市場性", "同一町内の戸建需要はあるが、狭隘道路と鉄塔隣接で買主は慎重。"],
        ["収益性・経済合理性", "開発転用より、戸建住宅地としての売買比較が価格判断の中心。"],
      ],
      conclusion: "結論: 標準的住宅地としての継続利用を前提に、取引事例比較法で比準価格を調整する。",
    },
    auditCriteria: {
      focus: "対象不動産の確定、事情補正、試算価格の調整が順につながっているか。",
      risk: "依頼者説明60坪や相続事情に引っ張られ、登記地積・接道・越境疑いを軽視していないか。",
      comment: "監査では、面積不一致を事実、親族間売買を分析、リスク調整を結論として提示できたかを見る。",
      requiredEvidence: ["areaMismatch", "specialTransaction", "riskAdjustment"],
    },
    adjustmentBands: [
      {
        id: "minor",
        label: "軽微な調整 -5%",
        detail: "内装や印象差を中心に見て、土地側リスクは小さく扱う。",
        correct: false,
        supportEvidence: ["wallCrack", "utility"],
        supportPrompt: "軽微調整を説明するなら、建物印象など土地価格への影響が薄い根拠に限られる。",
        scores: { appraisal: -3 },
        lesson: "面積不一致、接道、越境疑い、嫌悪施設を拾っているため、軽微な調整では説明が弱い。",
      },
      {
        id: "balanced",
        label: "標準的調整 -10%",
        detail: "対象確定と個別的要因を価格レンジ内で一貫して反映する。",
        correct: true,
        supportEvidence: ["areaMismatch", "road", "boundary", "tower"],
        supportPrompt: "標準的調整を支える価格形成要因を2枚選ぶ。",
        scores: { appraisal: 5, reasoning: 2 },
        mentor: "調整幅は根拠カードと整合している。過大でも過小でもなく、説明可能な減価だ。",
      },
      {
        id: "severe",
        label: "強い調整 -18%",
        detail: "不確実性を広く見込み、相続説明用に低めの安全側へ寄せる。",
        correct: false,
        supportEvidence: ["tower", "road"],
        supportPrompt: "強い調整を採るなら、通常以上に市場性を損なう根拠が必要になる。",
        scores: { appraisal: -2, ethics: -1 },
        lesson: "リスクを過大に積むと、根拠の範囲を超えた慎重評価になる。正常価格として説明できる幅に留める。",
      },
    ],
    rebuttalOptions: [
      {
        id: "areaProof",
        label: "登記地積と対象確定を再提示",
        detail: "面積不一致を先に閉じ、依頼者説明60坪を根拠にしない理由を返す。",
        requiredEvidence: "areaMismatch",
        correct: true,
      },
      {
        id: "familySympathy",
        label: "相続事情への配慮を強調",
        detail: "妹への説明事情を汲み、価格レンジの上限寄りで話をまとめる。",
        requiredEvidence: "pricePoint",
        correct: false,
        lesson: "相続事情は依頼目的であり、正常価格の根拠そのものではない。",
      },
    ],
    marketScenarios: [
      {
        id: "quietInheritance",
        title: "相続協議は早期決着志向",
        detail: "兄妹間の交渉は急いでいるが、市場条件自体は標準的。",
        appraisalHint: "面積差と接道を軸に、過度な安全側へ寄せない。",
        supportEvidence: ["areaMismatch", "road"],
      },
      {
        id: "buyerCaution",
        title: "近隣買主は接道に慎重",
        detail: "同町内で狭隘道路物件への買主反応が弱い。",
        appraisalHint: "接道と境界の根拠を厚めに置く。",
        supportEvidence: ["road", "boundary"],
      },
      {
        id: "utilityBurden",
        title: "改修買主は設備負担を警戒",
        detail: "古い住宅地で、給排水・外壁・境界確認の初期費用を買主が強く見る局面。",
        appraisalHint: "設備負担と外壁劣化を根拠に、標準的調整の説明を厚くする。",
        supportEvidence: ["utility", "wallCrack"],
      },
    ],
    tutorials: {
      0: {
        title: "まず覚えること",
        body: "鑑定士は依頼者の事情を聞いたうえで、説明できる価格の幅を判断する。最初に価格時点、対象不動産、価格の種類を固定する。",
        terms: ["価格時点: いつの価格か", "対象不動産の確定: 何を評価するか", "正常価格: 通常の市場で成立する価格"],
        next: "この面談では「正常価格として受任」を選ぶのが基本。",
      },
      1: {
        title: "現地調査の見方",
        body: "写真では、きれい/古いではなく、買主が価格で気にする要因を探す。",
        terms: ["個別的要因: 物件そのものの条件", "地域要因: 周辺環境の条件", "接道: 道路とのつながり"],
        next: "外壁、境界、鉄塔、道路の4つは特に価格に結びつけやすい。",
      },
      2: {
        title: "資料照合の見方",
        body: "資料は多くても、価格に効く矛盾だけを残す。面積差と取引事情は初心者でも見抜きやすい重要論点。",
        terms: ["事情補正: 特別な事情がある取引を補正する", "時点修正: 過去の取引を価格時点へ直す"],
        next: "登記55坪と依頼者60坪の差、親族間売買、18か月前の取引を確認する。",
      },
      3: {
        title: "価格判断の型",
        body: "最有効使用を標準的住宅地として確認したうえで、住宅地では取引事例比較法が中心。近い事例を選び、現地で見つけた減価要因を調整する。",
        terms: ["最有効使用: 合法・物理・市場・収益の面から最も合理的な使用", "取引事例比較法: 似た売買事例と比べる方法", "試算価格の調整: 複数の根拠を見て価格を整える"],
        next: "事例A、リスク反映、標準的調整を軸に考える。",
      },
      4: {
        title: "報告の型",
        body: "強い報告は、事実、分析、結論の順に並ぶ。全部のカードを出すのではなく、3枚で説明する。",
        terms: ["事実: 面積差や現地で見たこと", "分析: 事情補正や比較判断", "結論: 調整後の価格判断"],
        next: "面積不一致、事情補正、リスク調整の3枚を基本形にする。",
      },
    },
  },
  case002: {
    number: "案件 002",
    title: "駅前商業地 / 収益還元法",
    shortTitle: "駅前商業地",
    type: "収益物件",
    difficulty: {
      label: "ノーマル",
      code: "Normal",
      summary: "収益物件編。用語補助は残しつつ、純収益と利回りの判断を自分で組み立てる。",
    },
    image: "./assets/ekimae-commercial.generated.png",
    fallbackImage: "./assets/ekimae-commercial.svg",
    imageAlt: "駅前商業ビル外観。店舗、空室掲示、看板、修繕箇所、人通りが見える。",
    assetRefs: {
      fieldImage: "assets/ekimae-commercial.generated.png",
      clientPortrait: "assets/saeki-client.generated.png",
    },
    client: {
      name: "佐伯亮",
      initial: "佐",
      portrait: "./assets/saeki-client.generated.png",
      portraitClass: "portrait-saeki",
      tension: "借換融資を通したい不動産会社担当。利回りを低く見せる誘導をかける。",
      gameplayLines: {
        field: "空室はたまたまです。駅前立地の強さも見てください。",
        documents: "銀行には、安定したビルだと伝わる資料にしたいんです。",
        appraisal: "利回りひとつで評価額がかなり変わりますよね。説明できる範囲で低めに置けませんか。",
        report: "借換がかかっているので、弱く見える表現は避けたいです。",
      },
    },
    evidenceIds: [
      "incomePricePoint",
      "incomeSubject",
      "tenantMix",
      "vacancySign",
      "repairBacklog",
      "roadFlow",
      "signLease",
      "rentRoll",
      "expenseLeak",
      "capRateGap",
      "directCap",
      "incomeAdjustment",
    ],
    requiredReport: ["rentRoll", "capRateGap", "incomeAdjustment"],
    reportStructure: {
      fact: ["rentRoll", "expenseLeak", "vacancySign", "repairBacklog"],
      analysis: ["capRateGap", "directCap", "roadFlow"],
      conclusion: ["incomeAdjustment", "incomeSubject", "incomePricePoint"],
    },
    hbuMatrix: {
      title: "最有効使用の前提確認",
      lead: "商業地でも最有効使用は前提。ここでは、駅前の店舗・事務所複合ビルとして継続運用する前提が収益性と市場性に合うかを確認する。",
      rows: [
        ["法的可能性", "商業系用途として整合。現況ビル運用は法令面で大きな逸脱なし。"],
        ["物理的可能性", "築古で修繕負担あり。空調・外壁更新を純収益に反映する。"],
        ["市場性", "駅前動線はあるが、空室期間と裏通り化で賃料上限に注意。"],
        ["収益性・経済合理性", "更地化より、安定NOIを標準化した継続賃貸運用が価格判断の中心。"],
      ],
      conclusion: "結論: 店舗・事務所複合ビルとしての継続運用を前提に、収益還元法で収益価格を査定する。",
    },
    auditCriteria: {
      focus: "安定純収益、還元利回り、収益リスク調整が同じ収益前提で説明されているか。",
      risk: "満室想定や依頼者提示利回りに寄せて、空室損・修繕費・市場利回りを落としていないか。",
      comment: "監査では、レントロールを事実、利回り差を分析、収益価格調整を結論として提示できたかを見る。",
      requiredEvidence: ["rentRoll", "capRateGap", "incomeAdjustment"],
    },
    adjustmentBands: [
      {
        id: "optimistic",
        label: "薄い調整 -3%",
        detail: "駅前立地の強さを重視し、空室と修繕は短期要因として軽く見る。",
        correct: false,
        supportEvidence: ["tenantMix", "roadFlow"],
        supportPrompt: "薄い調整を採るなら、駅前立地やテナント構成の強さで支える必要がある。",
        scores: { appraisal: -4 },
        lesson: "空室と修繕費を短期要因に寄せると、純収益と還元利回りの説明が弱くなる。",
      },
      {
        id: "stabilized",
        label: "安定化調整 -8%",
        detail: "空室損、修繕費、市場利回りを標準化して収益価格へ反映する。",
        correct: true,
        supportEvidence: ["rentRoll", "expenseLeak", "capRateGap", "vacancySign"],
        supportPrompt: "安定化調整を支える収益根拠を2枚選ぶ。",
        scores: { appraisal: 6, reasoning: 2 },
        mentor: "安定純収益と市場利回りがつながった。融資希望額から切り離せている。",
      },
      {
        id: "distressed",
        label: "過度な調整 -15%",
        detail: "空室リスクを大きく見て、保守的な売却価格に寄せる。",
        correct: false,
        supportEvidence: ["vacancySign", "repairBacklog"],
        supportPrompt: "過度な調整を採るなら、継続的な空室と修繕負担を直接支える必要がある。",
        scores: { appraisal: -3 },
        lesson: "空室は重要だが、通常の収益物件として市場化できる範囲を超えて減価すると説明過剰になる。",
      },
    ],
    rebuttalOptions: [
      {
        id: "marketYield",
        label: "市場利回りと空室損で再反論",
        detail: "レントロールと還元利回り差を使い、依頼者の4%台希望を切り離す。",
        requiredEvidence: "capRateGap",
        correct: true,
      },
      {
        id: "bankTone",
        label: "銀行向け表現に丸める",
        detail: "融資審査で弱く見えないよう、利回り表現を曖昧にする。",
        requiredEvidence: "directCap",
        correct: false,
        lesson: "銀行向けの見え方に寄せると、収益価格の説明責任が崩れる。",
      },
    ],
    marketScenarios: [
      {
        id: "tenantChurn",
        title: "駅前でもテナント入替が増加",
        detail: "近隣商業地で小規模テナントの入替期間が長くなっている。",
        appraisalHint: "空室とレントロールを支える根拠にする。",
        supportEvidence: ["rentRoll", "vacancySign"],
      },
      {
        id: "repairCycle",
        title: "築古ビルの修繕費が上振れ",
        detail: "同規模ビルで設備更新費の見積が増えている。",
        appraisalHint: "必要諸経費と修繕滞留を支える根拠にする。",
        supportEvidence: ["expenseLeak", "repairBacklog"],
      },
      {
        id: "leaseDisclosure",
        title: "定期借家の開示精度が重視",
        detail: "投資家が賃貸借契約の継続性と空室化リスクを細かく確認している。",
        appraisalHint: "定期借家条項とテナント構成を報告根拠に入れる。",
        supportEvidence: ["signLease", "tenantMix"],
      },
    ],
    tutorials: {
      0: {
        title: "収益物件の入口",
        body: "商業ビルは、売買事例だけでなく、将来どれだけ安定して稼げるかを見る。",
        terms: ["純収益: 収入から経費や空室損を引いたもの", "還元利回り: 収益を価格へ変換する率"],
        next: "融資希望額ではなく、純収益と市場利回りを固定する方針で受任する。",
      },
      1: {
        title: "現地調査の見方",
        body: "収益物件では、建物の見た目よりも、賃料が続くか、空室や修繕が価格に効くかを見る。",
        terms: ["空室リスク", "必要諸経費", "テナント構成"],
        next: "空室掲示、修繕遅れ、テナント依存を優先して探す。",
      },
      2: {
        title: "収益資料の読み方",
        body: "満室想定は強く見えるが、空室損と修繕費を引いた安定純収益で見る。",
        terms: ["レントロール: 賃貸条件の一覧", "DCR: 借入返済に対する収益余裕"],
        next: "満室NOIから空室損と修繕費を控除して、安定NOIを検算する。",
      },
      3: {
        title: "収益価格の型",
        body: "最有効使用を店舗・事務所の継続運用として確認したうえで、安定純収益を市場利回りで還元する。",
        terms: ["最有効使用: 収益性だけでなく市場性・物理性・法令も見る", "直接還元法", "収益価格", "還元利回り"],
        next: "直接還元法、収益リスク反映、安定化調整を軸に考える。",
      },
      4: {
        title: "報告の型",
        body: "融資目的でも、鑑定士は銀行に通りやすい数字を作らない。収益資料と市場利回りで説明する。",
        terms: ["事実: レントロールや空室", "分析: 利回り差", "結論: 収益価格の調整"],
        next: "レントロール、還元利回り、収益価格調整の流れで説明する。",
      },
    },
  },
  case003: {
    number: "案件 003",
    title: "南口再開発予定地 / 開発法・最有効使用",
    shortTitle: "南口再開発予定地",
    type: "再開発予定地",
    difficulty: {
      label: "ハード",
      code: "Hard",
      summary: "上級編。用語補助は最小限。最有効使用、開発法、権利調整をまとめて判断する。",
    },
    image: "./assets/minamiguchi-redevelopment.generated.png",
    fallbackImage: "./assets/minamiguchi-redevelopment.svg",
    imageAlt: "駅南口の再開発予定地。古い倉庫、入居店舗、狭い路地、浸水表示、規制線が見える。",
    assetRefs: {
      fieldImage: "assets/minamiguchi-redevelopment.generated.png",
      clientPortrait: "assets/kurokawa-client.generated.png",
    },
    client: {
      name: "黒川航",
      initial: "黒",
      portrait: "./assets/kurokawa-client.generated.png",
      portraitClass: "portrait-kurokawa",
      tension: "地権者をまとめたい開発会社代表。最大容積案を既成事実にしようとする。",
      gameplayLines: {
        field: "今は古い街並みでも、計画後の姿を見てください。",
        documents: "行政協議は進めます。ここで弱く見られると地権者が動きません。",
        appraisal: "14階案を切ると事業性が全然変わるんです。可能性は残せませんか。",
        report: "最大容積を諦めたように読める評価書は困ります。",
      },
    },
    evidenceIds: [
      "redevelopmentPricePoint",
      "redevelopmentSubject",
      "tenantRights",
      "narrowAlley",
      "zoningMismatch",
      "floodHistory",
      "oldWarehouse",
      "zoningCheck",
      "relocationCost",
      "infrastructureBurden",
      "developmentMethod",
      "bestUseAdjustment",
    ],
    requiredReport: ["zoningCheck", "relocationCost", "bestUseAdjustment"],
    reportStructure: {
      fact: ["zoningCheck", "tenantRights", "narrowAlley", "zoningMismatch", "floodHistory"],
      analysis: ["relocationCost", "infrastructureBurden", "developmentMethod"],
      conclusion: ["bestUseAdjustment", "redevelopmentSubject", "redevelopmentPricePoint"],
    },
    hbuMatrix: {
      title: "最有効使用の中心判断",
      lead: "再開発予定地では、どの用途・規模で開発するのが最有効使用かが価格判断の中心になる。",
      rows: [
        ["法的可能性", "用途地域だけでなく、高度地区・斜線制限・道路後退で実現階数を絞る。"],
        ["物理的可能性", "狭い路地、浸水履歴、既存倉庫解体、搬入動線が開発規模を制約する。"],
        ["市場性", "駅前需要は強いが、住民説明とテナント移転が長期化すると買主はリスクを見る。"],
        ["収益性・経済合理性", "最大容積案ではなく、費用・期間・販売総額を控除した中層共同住宅＋低層店舗が妥当。"],
      ],
      conclusion: "結論: 最大容積14階案ではなく、実現可能な中層共同住宅＋低層店舗を前提に開発法で比較考量する。",
    },
    auditCriteria: {
      focus: "最有効使用マトリクスで、最大容積案を合法性・物理性・市場性・収益性の順に絞ったか。",
      risk: "依頼者の14階案をそのまま販売総額へ入れ、斜線制限・道路後退・立退き・浸水リスクを後回しにしていないか。",
      comment: "監査では、用途地域マップを事実、立退料・開発負担を分析、中層共同住宅＋低層店舗を結論として説明できたかを見る。",
      requiredEvidence: ["zoningCheck", "relocationCost", "bestUseAdjustment"],
    },
    adjustmentBands: [
      {
        id: "developerUpside",
        label: "開発期待調整 -5%",
        detail: "駅前再開発期待を重く見て、法規制と立退きの調整を薄く置く。",
        correct: false,
        supportEvidence: ["developmentMethod", "oldWarehouse"],
        supportPrompt: "開発期待を残すなら、販売総額と現況利用の継続性を支える必要がある。",
        scores: { appraisal: -5, ethics: -2 },
        lesson: "開発期待を先に置くと、最有効使用が依頼者計画へ引っ張られる。",
      },
      {
        id: "legalDiscount",
        label: "実現可能性調整 -12%",
        detail: "高度地区、道路後退、立退き、浸水履歴を開発法の前提へ反映する。",
        correct: true,
        supportEvidence: ["zoningCheck", "relocationCost", "infrastructureBurden", "floodHistory"],
        supportPrompt: "実現可能性調整を支える法規制・権利・開発負担カードを2枚選ぶ。",
        scores: { appraisal: 7, reasoning: 2 },
        mentor: "実現可能性で絞った調整幅だ。開発素地価格として説明しやすい。",
      },
      {
        id: "withdrawalRisk",
        label: "事業中止級調整 -25%",
        detail: "権利調整が長期化すると見て、開発をほぼ成立困難として扱う。",
        correct: false,
        supportEvidence: ["relocationCost", "floodHistory"],
        supportPrompt: "事業中止級まで下げるなら、権利調整と災害リスクが決定的である説明が必要になる。",
        scores: { appraisal: -3 },
        lesson: "不確実性はあるが、取得資料だけで事業中止級まで落とすと根拠を超える。",
      },
    ],
    rebuttalOptions: [
      {
        id: "legalConstraint",
        label: "高度地区・斜線制限で再反論",
        detail: "用途地域マップと実現階数の検算を根拠に、14階案をそのまま採れないと返す。",
        requiredEvidence: "zoningCheck",
        correct: true,
      },
      {
        id: "developerSchedule",
        label: "事業者工程表を条件付きで採る",
        detail: "住民説明や立退きは後続工程として、最大容積案を価格前提に残す。",
        requiredEvidence: "developmentMethod",
        correct: false,
        lesson: "事業者工程表は価格形成要因ではあるが、法令上・権利上の制約を上書きできない。",
      },
    ],
    marketScenarios: [
      {
        id: "residentDelay",
        title: "住民説明が長期化",
        detail: "近隣再開発で立退き交渉が長引き、事業期間リスクが強く意識されている。",
        appraisalHint: "立退料と開発負担を支える根拠にする。",
        supportEvidence: ["relocationCost", "infrastructureBurden"],
      },
      {
        id: "regulationWatch",
        title: "高度地区運用が厳格化",
        detail: "駅南口周辺で斜線・高度地区の事前協議が厳しく見られている。",
        appraisalHint: "用途地域マップと道路後退を支える根拠にする。",
        supportEvidence: ["zoningCheck", "narrowAlley"],
      },
      {
        id: "floodCost",
        title: "浸水対策費が事業収支を圧迫",
        detail: "同一駅圏で、地下ピット・止水板・保険料を織り込む買主が増えている。",
        appraisalHint: "浸水履歴とインフラ負担を支える根拠にする。",
        supportEvidence: ["floodHistory", "infrastructureBurden"],
      },
    ],
  },
},
  };
})();
